### ISSUE TITLE
Ball go across ground

### ISSUE THREAD

**Issue by damienaguerre** [chandlerprall/Physijs#102]
Hi !

I've implemanted a little scene with some walls.

To click on the page, I create and launch a ball with the setLinearVelocity() method.

But sometimes (most of the time), the ball go across the walls or the ground.

I don't understand why..

You can test here : http://akimad.com/pilota/

Thank you in advance for your help (and sorry for my bad english ^^')

**Comment by ZhaoRuiTao** [comment]
good
