### ISSUE TITLE
Check if object is placeable / buildable

### ISSUE THREAD

**Issue by Doidel** [chandlerprall/Physijs#155]
Hi

First of all thanks for the great library. It's very helpful and it would be a shame to see it land in the dust, I hope support and development will continue!

I wanted to test if an object is "placeable" at a current location, meaning whether there would be a collision / overlapping or none.
My initial thought is to do this with enabling and disabling the object's physics over and over, e.g. enabling it periodically and disabling it as soon as a collision is registered. Is that a good idea or is there a better approach to do this?

Thanks in advance for some thoughts!

Kind regards
Doidel

**Comment by a735561656** [comment]
Have you solve the question  .please email me to 735561656@qq.com
