### ISSUE TITLE
Create pass-through-able object?

### ISSUE THREAD

**Issue by rubencodes** [chandlerprall/Physijs#187]
Hi,

I was wondering if there was a way to create an object that could be passed-through. Think like a ghost through a wall. And ideally with collision detection still intact. Thoughts?

I'm working on a game and trying to create something akin to a coin in a Super Mario game--something I can touch without it having any effect on my or its trajectories, but that I can detect that I touched it so as to gain points. 

Thanks for the help!

**Comment by rococtz** [comment]
@Doidel, I know it's more than 2 years, but was the `collision_flags` property removed? I want to try your solution, but I can't find that property anymore.
