### ISSUE TITLE
Need to update packaged three.min.js so that examples work

### ISSUE THREAD

**Issue by jamestinman** [chandlerprall/Physijs#200]
Calls to BoxMesh don't work in the examples because the packages three.js is out-of-date. Checked it with the latest r68, works a treat!

**Comment by daoshengmu** [comment]
Yep. you can consider to use three.js version 71. If you need someone to help you upgrade it, I can help you!

**Comment by jamestinman** [comment]
Thanks (delayed response, sorry!)
