### ISSUE TITLE
Setting a maximum velocity on object

### ISSUE THREAD

**Issue by glennflanagan** [chandlerprall/Physijs#226]
Hi there I am working with a simple box which I'm applying an impulse each frame to get it moving using 

```javascript
character.applyCentralImpulse({x: 1, y: null, z: null});
```

However I want to restrict it's velocity in a direction so it doesn't just fly off - but I can't figure out a way of doing this as I can't find anything in the documentation.

Is this possible with Physijs?

**Comment by chandlerprall** [comment]
You'll have to check the object's velocity after every step and adjust accordingly. There is nothing in the engine itself to limit velocity.

**Comment by schteppe** [comment]
@chandlerprall I guess this should be done for each internal tick in Ammo? Otherwise it would be frame rate dependent :(

**Comment by glennflanagan** [comment]
So my character also is able to jump where I am applying an impulse on the Y axis.

```javascript
character.applyCentralImpulse({x: null, y: 15, z: null});
```

And to limit the velocity on the X axis I would need to do something like this

```javascript
if(character.getLinearVelocity().x > 15){
    character.setLinearVelocity({x: 15, y: null, z:null});
}
```

But the issue I have with that is it causes the character to float when it's 'Jumping' and you set the velocity on the X axis passing null as the Y and Z values.

Am I approaching this the wrong way or are there other Phyisjs methods hidden away that I'm not aware of?

Thanks

**Comment by chandlerprall** [comment]
@schteppe that's true, unfortunately setting up emscripten callbacks is a huge pain and not something I'm willing to add. Physijs can be configured to only perform one step at a time.

@glennflanagan you'll need to set the `y` and `z` velocities to match what they are and not set only `x`. Alternatively you could use `applyCentralImpulse` and pass the difference between target and current `x` velocity; this would ensure only `x` is affected.

**Comment by glennflanagan** [comment]
@chandlerprall 
Thanks, that seemed to do the trick. Had to do this in the end

```javascript
                        //running right
			if(character.getLinearVelocity().x > 15){
				character.setLinearVelocity({x: 15, y: character.getLinearVelocity().y, z:character.getLinearVelocity().z});
			}
			//running left
			if(character.getLinearVelocity().x < -15){
				character.setLinearVelocity({x: -15, y: character.getLinearVelocity().y, z:character.getLinearVelocity().z});
			}
```
