### ISSUE TITLE
Collision Event Not Being Called

### ISSUE THREAD

**Issue by reggie3** [chandlerprall/Physijs#236]
I'm creating a physi.js object like so:

    this.shapeColor = this.colors[colorIndex];
    // Box
    var shapeMaterial = Physijs.createMaterial(
        new THREE.MeshLambertMaterial({
            color: this.boxColors[colorIndex]
        }),
        1,
        .0 
    );
    this.physiShape = new Physijs.BoxMesh(
        new THREE.BoxGeometry(boxWidth, boxHeight, boxDepth),
        shapeMaterial,
        5
    );
    this.physiShape.collisions = 0;
    
    var that = this;
    var readyHandler = function () {
        console.log("shape ready");
        bolReadyForNewShape = true;
        that.physiShape.setAngularFactor(new THREE.Vector3());
        that.physiShape.setLinearFactor(new THREE.Vector3(1, 1, 0));   
    };
    var collisionHandler = function(){
        console.log("collision");
    };
    this.physiShape.addEventListener('ready', readyHandler);
    this.physiShape.addEventListener('collision', collisionHandler);

The collision callback is never called.  However, the ready callback is called properly as well as a scene.update callback in a different section of code.  I've also tried to technique indicated in issue 244, by not touching the object's angular and linear factors, but that made no difference.  I've copied the ammo.js file from the examples folder as well as using the most current build of ammo.js and that also made no difference.

**Comment by jopango** [comment]
I'm actually having the same issue since I started to work again on a project I worked on some months ago, in which collisions used to work. I now use r71 of three.js, instead of r70 previously, but I doubt that it's the reason of this issue...
