### ISSUE TITLE
Error: _object.setWorldTransform is not a function

### ISSUE THREAD

**Issue by ilanusse** [chandlerprall/Physijs#237]
Hello!

Physijs is not updating my mesh's position and rotation even though I am setting the __dirty flags to true.

My code is as follows: 

``` javascript
this.mesh.position.y = position;
this.mesh.setRotationFromQuaternion(quaternion);
this.mesh.__dirtyPosition = true;
this.mesh.__dirtyRotation = true;
```

And yet I get the following error:

`_object.setWorldTransform is not a function`

The function throwing the error is `updateTransform` in `physijs_worker.js`.

I'm using `threejs r71`.

**Comment by InitialCrow** [comment]
i add the same problem do you find the response ??

**Comment by JSideris** [comment]
This is still a problem in 2019. I solved it by removing the object from the scene, moving it, and re-adding it back to the scene. The __dirtyPosition does not need to be set if you do this.
