### ISSUE TITLE
RTS vehicle movement suggestions?

### ISSUE THREAD

**Issue by emnh** [chandlerprall/Physijs#239]
I have a small [RTS demo](http://alexis.lart.no/emh/rts-snapshot1.git/).

There are some tanks moving around, just Physijs boxes, not Physijs vehicles yet.
Currently they get stuck trying to move into the ground, because I'm not checking that there is contact with ground before applying force in the direction of unit rotation. I use applyCentralImpulse, and struggled a bit to find the right number 1e8 to get tanks moving. Couldn't get applyCentralForce to work, although it sounds more correct to use.

I need a few properties, but generally what I'm looking for is less realism, more RTS-like movement:
 - Vehicles need to stay stable and upright, not fall over on the back side. Current hack seems to handle it partially by setting x and z angular velocity to 0.
 - Vehicles should not apply force without contact with ground. I guess I should calculate the distance between bounding box and ground and check it, or use vehicle class with wheels. Maybe Physijs collision handling can inform it?

I'm thinking maybe I should raycast or somehow trace a path in the terrain and just move at constant speed along it instead of using a physics engine, but I like that the engine gravity takes care of alignment and rotation with terrain. How can I mix and match to get the best of physics while getting more RTS-like movement?

Would it be better to use the Physijs vehicle class? I think tanks can still get stuck and fall over.
How does it perform with hundreds of units?

One option is to make the terrain more level to reduce problems with getting stuck, but is more boring..

What are your general thoughts and suggestions?

**Comment by emnh** [comment]
I [implemented vehicles](http://alexis.lart.no/emh/rts-vehicles.git/). Looks quite bad: vehicles get stuck sometimes, they fly too much and don't fall fast enough, plus I disabled rotation because of too much spinning so tanks are not aligned with terrain. Also FPS is low. Perhaps custom RTS physics are needed.

**Comment by devlinjd** [comment]
Is there a reason why you need physics support for the tanks at all? It adds quite a bit of overhead. If you're talking hundreds of box-like units I think you'd be better off avoiding Physijs and all generic physics libs and programming the behaviors yourself. Especially if you're only using Physijs for stuff like ground contact.

Under no circumstances would I use the Physijs vehicle stuff. It's a mess.

**Comment by emnh** [comment]
Yeah I ended up coding some simple tank movement instead of using Physijs. Performance is much better now :)
