### ISSUE TITLE
changing material properties in runtime

### ISSUE THREAD

**Issue by speculees** [chandlerprall/Physijs#257]
Hello,
nice work with Physijs. I was wondering is it possible to change material properties in runtime, such as friction, mass and restitution. I tried changing the material object attribute values, and creating a new object. Everything looks okay in inspector. The object attributes have correct values, however the Physijs seems to ignore them. 
Also, I noticed that gravity has strange behavior. Vector(0,0,0) works as expected, but when y is negative the amount makes no difference. It can be -9.81 or -9810000... I will set up example soon.

**Comment by peterjwest** [comment]
Gravity works perfectly for me.

**Comment by speculees** [comment]
@peterjwest , you are right. It does work. I noticed that when I switched to a better PC. It was just difficult to notice such subtle changes on low end hardware. Thanks for the reply.

**Comment by speculees** [comment]
Changing the whole physics mesh instead of material worked for me. First I remove the meshes from scene and load them again with different material attributes, Marking this as closed.
