### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by jangdan** [chandlerprall/Physijs#262]
Do you have plans to publish this to npm? There seems to be an unofficial project that does just that, but it seems outdated: [https://github.com/silviopaganini/physijs-browserify](url)

Physijs isn't in good shape (judging by the amount of un-merged pull requests). I hope this project could be worked on a little more.

**Comment by escapedcat** [comment]
I think the [version 2 branch](https://github.com/chandlerprall/Physijs/tree/2.0) is preparing this.
[Here's the package.json](https://github.com/chandlerprall/Physijs/blob/2.0/package.json) already.

**Comment by chandlerprall** [comment]
@escapedcat is correct; Physijs v2 will be available on npm

**Comment by jangdan** [comment]
Oh cool! I overlooked the 2.0 branch. I guess I'll just manually include for now.
When would we be expecting version 2 then?

**Comment by escapedcat** [comment]
Linking #213 here.
