### ISSUE TITLE
wrong path for  physijs_worker.js and ammo.js

### ISSUE THREAD

**Issue by leonardopaiva** [chandlerprall/Physijs#280]
Hey, i`m new with threejs and this lib... i was trying to make a basic example and it took some time to realize this:

Physijs.scripts.worker = 'physijs_worker.js';
Physijs.scripts.ammo = 'ammo.js';

the path was wrong, and no error message. My suggestion is to console log  an error message, this way will be more easy to identify the problem.

congratulations for this fantastic library

**Comment by msundquist** [comment]
Seconding this. Basically the examples you get after downloading the package don't work at all unless you fix the code yourself. Kind of looks bad. We need the ThreeJS community to get behind PhysiJS and make it the library we deserve! ;-)

**Comment by mmmovania** [comment]
For the latest version of physijs, the path to ammo.js is relative to the physi_worker.js script file. If both ammo.js and physi_worker.js are inside js subfolder, u should set the paths like this
`Physijs.scripts.worker = "js/physijs_worker.js";
Physijs.scripts.ammo="ammo.js"`
For others who are finding it difficult, i am doing a simple collection of tutorials which will hopefully help. Url: https://github.com/mmmovania/Physijs_Tutorials

**Comment by leonardopaiva** [comment]
hey, thanks for the tutorials.
