### ISSUE TITLE
Rendering stopped working on Chrome 54

### ISSUE THREAD

**Issue by erosmarcon** [chandlerprall/Physijs#288]
I've found that previously working physijs projects  (even this basic example: https://github.com/chandlerprall/Physijs/wiki/Basic-Setup) stopped working with the latest Chrome version (54.0.2840.71) on Mac OSX (not tried windows yet) and the latest Three.js release.
Loops are running and I can see stats updates but nothing gets rendered.
Everything works fine with Firefox. 
Has anyone experienced the same issue?

**Comment by TimDix** [comment]
I'm also using 54.0.2840.71 (64-bit) on Mac OSX, all demos are working fine for me.

**Comment by erosmarcon** [comment]
Demos viewed from the website are ok for me too...
But they rely on Three r. 60 (very old). 
I've used physis with Three until v.80 and everything worked fine in Chrome too until v.54.
Communication with web worker is ok (I can log the messages) and Stats are running for both physics and three loops.
I had no time yet to test with other platforms, but if i revert back to Chrome 53 with the same three dependency everything works fine. I'll investigate more in depth. Thank you.

**Comment by erosmarcon** [comment]
Probably this is not the best place here to continue, but it seems a problem related to worker 
Let's have a look at another example using another physics library (cannon) with worker:

http://schteppe.github.io/cannon.js/examples/worker.html
Works well on FF but is blank on Chrome

And this is a Physi.js case:
http://www.uxvision.it/ph/test.html

**Comment by mmmovania** [comment]
Could you try running [these ](https://github.com/mmmovania/Physijs_Tutorials) tutorials and see if it helps? I have tested these on chrome and ffox latest versions.
