### ISSUE TITLE
physijs still updating?

### ISSUE THREAD

**Issue by leonardopaiva** [chandlerprall/Physijs#297]
Hello, I see that physijs is some time without update (Latest commit 7a53726  on Oct 20, 2015), is still recommend the use of physijs? Any other recommendations?

**Comment by ghost** [comment]
I'm working on [trebuchet.js](https://github.com/CuboidGame/trebuchet.js), which is quite similar to Physijs but is not tied to three.js. I'd recommend watching it and trying it out as soon as it reaches a stable version. But being the author, I guess that's no surpise :wink:

**Comment by leonardopaiva** [comment]
thanks i will take a loot at trebuchet

**Comment by neilsxD** [comment]
What some short of hacker r u !?!?
