### ISSUE TITLE
how to add physijs to js model ?

### ISSUE THREAD

**Issue by mika-co** [chandlerprall/Physijs#30]
hi guys 
i need add physijs to my game
this is my code
    loader.load( "models/kaf.js", function(geometry) {
        var part1 = new THREE.Mesh( geometry, new THREE.MeshFaceMaterial() );
        mesh = new THREE.Object3D();
                        mesh.add( part1 );
        //var mesh = new THREE.Mesh(geometry, material);
        mesh.position.set(0,80.10012515644638,0);
        mesh.rotation.set(0,0,0);
        mesh.scale.set(1,1,1);
        scene.add( mesh );
    });

**Comment by TitikshaDaga** [comment]
@chandlerprall how can I use Physijs for ionic framework?

-Thanks in advance!
