### ISSUE TITLE
Fixing the demo

### ISSUE THREAD

**Issue by bsamadi** [chandlerprall/Physijs#34]
I had to change the lines 19 and 20 in the html files of the demos to the following to make it work:

```
Physijs.scripts.worker = 'js/physijs_worker.js';
Physijs.scripts.ammo = 'ammo.js';
```

Did I miss anything?

Thanks,
Behzad

**Comment by user157** [comment]
I downloaded and unziped chandlerprall-Physijs-58ea99c I started html file but its not showing images .How to run these examples on local server
