### ISSUE TITLE
Setting relative angular velocity

### ISSUE THREAD

**Issue by fireph** [chandlerprall/Physijs#41]
I can't seem to get setting angular velocity relative to current position and rotation to work. Below is some of the code that I have: 

``` javascript
var zeroV = new THREE.Vector3(0,0,0);
var camVector = zeroV;

function projCalc(thetax, thetay, thetaz, cx, cy, cz, dx, dy, dz) {
    var M1 = $M([
        [1, 0, 0],
        [0, Math.cos(thetax), -1*Math.sin(thetax)],
        [0, Math.sin(thetax), Math.cos(thetax)]
    ]);
    var M2 = $M([
        [Math.cos(thetay), 0, Math.sin(thetay)],
        [0, 1, 0],
        [-1*Math.sin(thetay), 0, Math.cos(thetay)]
    ]);
    var M3 = $M([
        [Math.cos(thetaz), -1*Math.sin(thetaz), 0],
        [Math.sin(thetaz), Math.cos(thetaz), 0],
        [0, 0, 1]
    ]);
    var C = $M([
        [cx],
        [cy],
        [cz]
    ]);
    var D = $M([
        [dx],
        [dy],
        [dz]
    ])

    var M123 = M1.x(M2).x(M3);
    var M123inv = M123.inv();
    var result1 = M123.x(C).add(D);
    var result2 = M123inv.x(result1);
    return result2;
}

var otherEnd = projCalc(rotx, roty, rotz, camx, camy, camz, -1, 0, 0);
var unitVX = (otherEnd.elements[0][0] - camx);
var unitVY = (otherEnd.elements[1][0] - camy);
var unitVZ = (otherEnd.elements[2][0] - camz);
camVector.x = unitVX;
camVector.y = unitVY;
camVector.z = unitVZ;

camera.physics.setAngularVelocity(camVector);
```

camx, y, z is the position of the object that is going to be given the angular velocity

rotx, y, z is the current rotation of the object that is going to be given the angular velocity

and -1, 0, 0 is the relative axis of rotation

all projCalc() does is give the point that is (-1,0,0) in the relative space in the global coordinate plane (I used Sylvester to do the matrix math)

But whenever I try to set the angular velocity, it only works properly when the rotation is around 0 otherwise it is horribly wrong.

If there is an easier way to do this, that would be helpful! As a side note, it would be awesome if there could be a relative setAngularVelocity and getAngularVelocity in Physijs so that velocities could be changed relative to an objects current rotation.

Thanks

P.S. These are just code snippets above. My init and animate functions work just fine so that is not one of my issues.

**Comment by shawnwhinnery** [comment]
Bummer that link is dead.

**Comment by kellycode** [comment]
Maybe this one, but it seems broken atm: http://www.chandlerprall.com/labs/Physijs/examples/relative_velocity.html
