### ISSUE TITLE
Physijs on node

### ISSUE THREAD

**Issue by Doidel** [chandlerprall/Physijs#97]
Greetings

We're considering switching to physijs from cannon.js because the latter misses a heightfield implementation. Yet using workers on node is a complicated issue (c++-dependant feature has to be compiled for every platform individually, and it's buggy) and comes with no real benefits for us since we have a time based step-approach anyway (and sending the results to the client). Is there a way to use physijs without workers? And do you see any further problems with using physijs on the server?

Thanks in advance for some guidance!

**Comment by luddensdesir** [comment]
Crap, I definitely need help with this, hahah. I set up simple server-side simulation that calls simulate based on a game loop. However, the physics aren't actually running, even though I've  injected the webworker-threads into the Physijs module:
 
	var Worker = require('webworker-threads').Worker;
	var THREE = require('three');
	var Ammo = require('../node_modules/ammo/ammo.js');
	var Physijs = require('../node_modules/physijs/physi.js')(THREE, Ammo, Worker);


The physics are totally frozen, and either I get rid of workers completely, or just use Ammojs at this point!
